name: Build, Lint and Test

on: [push, pull_request]

concurrency:
  group: build_lint_and_test
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # the Node.js versions to build on
        node-version: [lts/*, lts/-1, lts/-2]

    steps:
      - uses: actions/checkout@v6

      - name: Use Node.js ${{ matrix.node-version }} 
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Lint the project
        run: npm run lint

      - name: Build the project
        run: npm run build
        env:
          CI: true

      - name: Test the project
        run: npm run test